version: '2.1'
services:
     elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
       container_name: elasticsearch
       ports:
          - "9200:9200"
          - "9300:9300"
       networks:
           docker-elk:

     kibana:
       image: docker.elastic.co/kibana/kibana:6.5.4
       container_name: kibana
       ports:
          - "5601:5601"
       environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"
       networks:
          - docker-elk
       depends_on:
          - elasticsearch

networks:
  docker-elk:
    driver: bridge

