version: '3'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: liquid
      MONGO_INITDB_ROOT_PASSWORD: liquid@2016
    volumes:
      - /data/.databases/mongo:/data/db

