version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql  # or `postgres`
            active: true
            host: db
            port: 3306        # or `5432` for `postgres`
            user: root
            password: graphcool
  db:
    container_name: prisma-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: graphcool
    ports:
    - 3306:3306
    volumes:
    - /data/.databases/.MYSQL/.DATA:/var/lib/mysql
    - /data/.databases/.MYSQL/.LOGS:/var/log/mysql
    - /data/.databases/.MYSQL/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

    entrypoint: ""
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"

